apiVersion: v1
kind: Service
metadata:
  name: {{ template "stolon.proxy.fullname" . }}
  labels:
    app: {{ template "stolon.proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: proxy
spec:
  {{ if .Values.proxy.serviceType }}
  type: {{ .Values.proxy.serviceType }}
  {{ end }}
  ports:
    - port: {{ .Values.ports.externalPort }}
      targetPort: {{ .Values.ports.internalPort }}
  selector:
    component: proxy
    stolon-cluster: {{ template "stolon.clusterName" . }}
