apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "stolon.sentinel.fullname" . }}
  labels:
    app: {{ template "stolon.sentinel.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: sentinel
spec:
  replicas: {{ .Values.sentinel.replicas }}
  template:
    metadata:
      labels:
        # Due to https://github.com/sorintlab/stolon/pull/433/commits/38ae6b13b5e161a5bfe0fbe01084ca060eaf2e76#diff-95cdd374e9440fde010ff35d65f8cf3fR54
        {{- if eq .Values.store.backend "kubernetes" }}
        app: "stolon-sentinel"
        {{- else }}
        app: {{ template "stolon.sentinel.fullname" . }}
        {{- end }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        component: sentinel
        stolon-cluster: {{ template "stolon.clusterName" . }}
        stolon-sentinel: "true"
    spec:

{{- if .Values.sentinel.affinity }}
      affinity:
{{ toYaml .Values.sentinel.affinity | indent 8 }}
{{- end }}

{{- if .Values.sentinel.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentinel.nodeSelector | indent 8 }}
{{- end }}

{{- if .Values.sentinel.tolerations }}
      tolerations:
{{ toYaml .Values.sentinel.tolerations | indent 8 }}
{{- end }}

      containers:
      - name: {{ template "stolon.sentinel.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            exec gosu stolon stolon-sentinel
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: STSENTINEL_CLUSTER_NAME
            value: {{ template "stolon.clusterName" .}}
          - name: STSENTINEL_STORE_BACKEND
            value: {{ .Values.store.backend | quote}}
          {{- if eq .Values.store.backend "kubernetes" }}
          - name: STSENTINEL_KUBE_RESOURCE_KIND
            value: {{ .Values.store.kubeRessourceKind  | quote}}
          {{- else }}
          - name: STSENTINEL_STORE_ENDPOINTS
            value: {{ .Values.store.endpoints | quote}}
          {{- end }}
          - name: STSENTINEL_DEBUG
            value: {{ .Values.debug | quote}}
        resources:
{{ toYaml .Values.sentinel.resources | indent 10 }}
